### ISSUE TITLE
Is the plugin still working in Sketch 45?

### ISSUE THREAD

**Issue by VaiteLR** [nefaurk/select-parent-artboards#5]

**Comment by nreliu** [comment]
Seems like it's working for regular artboards. It used to work for Symbol artboards too, but not anymore. Would it possible to bring this functionality back?

**Comment by VaiteLR** [comment]
It works when I select a layer that is not a symbol on an artboard. When I select a symbol, everything gets unselected. Sadly, almost all my layers are symbols! 
I tried to downgrade back to Sketch 44, just for this plugin and the 10 other plugins that stopped working. However it didn't work: because I'd already edited a Sketch file in 45, that file would not open anymore in Sketch 44. 
Please provide an update when this plugin is fixed.

**Comment by Murrzeak** [comment]
Yeah, stopped working for me too.

**Comment by nefaurk** [comment]
Thanks for spotting this, y'all! There are two issues:

1. The plugin doesn't work when you select a symbol within an artboard (tracked here: https://github.com/nefaurk/select-parent-artboards/issues/6)
2. The plugin doesn't work when you select layers within a symbol master artboard (tracked here: https://github.com/nefaurk/select-parent-artboards/issues/7)

Both of these issues are related to some API changes that I wasn't aware of. Since both issues are captured elsewhere, I'm going to close out this task.
